### PR TITLE
Update QEverCloud to 2.2-dev

### PR DESCRIPTION
**Pull request by gzm55**
1. Update QEverCloud, using new maintaining fork from  d1vanov
2. update the project file
3. re-create Makefile

### CODE REVIEW

**Comment by baumgarr** [comment]
Should be merged.  Let me know if (or what) I messed up.

**Comment by HoldingHands** [comment]
Hello Friend,

I’ve had trouble loading Evernote on Ubuntu, is there a more Nixnote friendly distro?
Please tell how having a prime account effects Nixnote.
I am very grateful for your efforts, and if you will help me get Evernote running well on Linux I will
gladly contribute to your work!

Thank you kindly,

Paula

**Comment by baumgarr** [comment]
What issues are you having on Ubuntu?  There are others who are using it.  I use a Kubuntu.  If you have issues I'd recommend opening an issue rather than commenting in a closed pull request.  Odds are I'll forget about it.  :)

Having a plus or premium account should work the same as a free account.  The "plus" features of Evernote don't mean anything to NixNote since they deal with Evernote server or mobile settings. 

The business settings are not implemented, but if Evernote sends indexing information to the local account you can search Office docs.  I don't have a business account so I haven't tested it.  Other things can't be done in NixNote, but if they are done in Evernote the contents can be synchronized with NixNote.

Work chat isn't supported in NixNote.

**Comment by rodrigoccurvo** [comment]
I've been trying to use a compiled version of Nixnote2 from the latest source and login isn't working. After poking around the code, I noticed that this change might be related to my problem. The error I'm getting is:

```
QObject::connect: Incompatible sender/receiver arguments
        qevercloud::ReplyFetcher::replyFetched(qevercloud::ReplyFetcher*) --> qevercloud::EvernoteOAuthWebView::temporaryFinished(QObject*)
```

In oauth.cpp the connect call changed the signature of the signal, so it doesn't match the slot's signature anymore: https://github.com/baumgarr/nixnote2/commit/a6be07af652de4e87ebfc6d435f62bc417f24031#diff-aaf80b74b65b6cbd2b4fe40dea462060R80 

I'm not sure if there's a purpose to that change, but...

To replicate the problem, all I have to do is, having a clean config:
1. Build code from latest source (github)
2. Run built nixnote2
3. Click on sync

Result: blank dialog and the message above on the console.

**Comment by d1vanov** [comment]
It is actually a problem of QEverCloud, I overlooked this when I was returning back the support for Qt4. I have fixed it [just now](https://github.com/d1vanov/QEverCloud/commit/d738f7f7fe040b4235eb0618f975254f00180358) in QEverCloud and bumped the library version to 2.2.1. Please try it, it should solve the problem.

**Comment by rodrigoccurvo** [comment]
I cherry-picked the change and now it seems to be working. Thank you!

**Pull request closed without merging**
