### PR TITLE
Add error logs when uploading tags, format messages

### PR DESCRIPTION
**Pull request by gzm55**

### CODE REVIEW

**Comment by baumgarr** [comment]
I'm not understanding how the QLOG_ERROR().maybeSpace() works.  Where is
that coming from?

**Comment by gzm55** [comment]
QLOG_ERROR() is defined as a expr returning a QDebug value, as described in http://doc.qt.io/qt-4.8/qdebug.html#maybeSpace, it will append a space char if the last character is not space.

**Comment by baumgarr** [comment]
Thanks for the clarification.  I didn't understand fully the changes in
qslog.h so I was confused when I tried to do a QLOG_ERROR().noSpace().

Thanks again!

**Comment by gzm55** [comment]
in qslog.h, the braces will make QLOG_ERROR() as a QDebug value in any case.

**Pull request merged**
