### PR TITLE
Restart sync on API & Themes improved

### PR DESCRIPTION
**Pull request by evaldsurtans**
1. Implemented proper way to sync notes after "API rate limit exceeded". Now it will ensure that notes will be synced as soon as possible. In my case without this update as a new user it will take forever to sync +10k notes by repeated press of Sync button or improper time intervals by hour as it was before.

In preferences must be enabled Sync > Restart sync on API limit (experimental)

I also advise to enable this function by default for new users.

2. Improved theme building options - code for styleheets & color overrides.
Implemented new theme for Mint-Y-Dark Theme (https://github.com/erikdubois/Ultimate-Linux-Mint-18-Cinnamon) that is included out of box in Linux Mint Version 18.

It looks like this:
http://storage5.static.itmages.com/i/17/0404/h_1491319234_8354525_9ac03dff84.png

If you want you could add me to contributors so that I could develop directly in development branch.

### CODE REVIEW

**Comment by evaldsurtans** [comment]
Why didn't you merge my changes? I did not change dependencies. Just improved code.

**Comment by evaldsurtans** [comment]
:) ?

**Comment by vitaly-zdanevich** [comment]
Thank you for improving theming!

**Comment by evaldsurtans** [comment]
hmm, will you merge these changes? I could make more improvements in future, but it's no point if you do not merge changes.

**Comment by danielmaurer** [comment]
This is a comment in the forum of the Mr. Randy: "Sorry for the slow response. I've been busy with other things & haven't had much time for NixNote. Hopefully I'll have time in a week or two to get back to this."
Thanks!

**Comment by baumgarr** [comment]
Thanks for the help. I'm truly sorry for the delay.

**Pull request merged**
